### ISSUE TITLE
Missing styling for installButton in Chapter 2

### ISSUE THREAD

**Issue by bcd55** [johnwargo/learning-pwa-code#2]
I've just started working through the examples in the book and am finding it very informative and well organized. I found a problem in Chapter 2, however, that causes some confusion. The section on **Enhancing the Installation Process** has a note that the styling for the installButton is already included in main.css, but it's not. That causes the butoon to appear even on browsers that don't support the install event and even after installing on those that do. I added the following to main.css to make it work as expected:

`  #installButton {
	display: none;
}`

**Comment by johnwargo** [comment]
@bcd55 thanks for opening the issue. You're right, the start project is missing the CSS.

the project's `css/main.css` file should have the following:

```css
#installButtonDiv {
  position: absolute;
  top: 1vh;
  right: 2vw;
}

button#installButton {
  background-color: rgb(54, 83, 179);
  color: white;
  padding: 1.3vw 1.6vw;
  font-size: 1.5vw;
  cursor: pointer;
  border-radius: 5px;
  display:none;
}

button#installButton:hover {
  background-color: #f87a03;
}
input {
  border: 1pt solid #ccc;
}
```

I'll copy over the file from the end project, that should fix this. Can you test it out and let me know?
